plugins:
  is_znb_plugin: {}
devices:
  znb:
    type:         socket
    address:      localhost
    port:         5025
    timeout:      2
init:
  - znb: "*RST"
  - znb: "*CLS"
  - znb: "*WAI"
  - znb: SENS:SWE:TYPE LIN
  - znb: SENS:FREQ:STAR 1 GHz
  - znb: SENS:FREQ:STOP 2 GHz
  - znb: SENS:SWE:POIN 201
start_sweeps count:
  - znb: INIT:CONT 0
  - znb: SENS:AVER 1
  - znb: SENS:AVER:COUN {count}
  - znb: SENS:SWE:COUN  {count}
  - znb: INIT
sweep_finished?:
  - znb: "*OPC?"
data?:
  - znb: CALC:PAR:SEL 'Trc1'
  - znb: CALC:DATA? FDAT
error?:
  - znb: SYST:ERR?
local:
  - znb: "@LOC"
