#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# tests pass?
scripts/install-dev
scripts/test

# release
scripts/clean
scripts/build
scripts/dist
